### PR TITLE
Update to new deploy redirector

### PR DESCRIPTION
**Pull request by jamesward**

### CODE REVIEW

**Comment by Timtech4u** [comment]
Hi @jamesward  👍  , thanks for making this update.
You can find the tutorial which this repo was based on [here](https://fullstackgcp.com/building-a-flaskpython-crud-api-with-cloud-firestorefirebase-and-deploying-on-cloud-run-cjzwbwvid000fpxs10npcr2ps)
I would like to send you a private message if you don't mind :)

**Comment by jamesward** [comment]
Thanks! Feel free to email me.

**Comment by jamesward** [comment]
Oh, and you should be able to update your tutorial to just link to `https://deploy.cloud.run`  Then they won't have to update the git url.

**Comment by Timtech4u** [comment]
Awesome, I would do that right away!
Thank you.

**Pull request merged**
